version: "3"

volumes:
  mysql_volume:

services:

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - customNetwork

  dbmysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "mspass"
      MYSQL_DATABASE: "equipment"
      MYSQL_USER: "msuser"
      MYSQL_PASSWORD: "mspass"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_volume:/data/db
    networks:
      - customNetwork

  app:
    build: .
    restart: always
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      MYSQL_USER: "root"
      MYSQL_PASS: "mspass"
      MYSQL_HOST: "dbmysql"
      MYSQL_PORT: "3306"
      MYSQL_DB: "equipment"
      APP_HOST: "0.0.0.0"
    ports:
      - 8080:8080
    networks:
      - customNetwork

    depends_on:
      - dbmysql
      - redis

networks:
  customNetwork: