"""added soft delete column

Revision ID: df0457ece091
Revises: f9c8f754d7cf
Create Date: 2023-05-21 19:27:24.031257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0457ece091'
down_revision = 'f9c8f754d7cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'is_deleted')
    # ### end Alembic commands ###
